In [1]:
import polars as pl

In [2]:
def clean_df(df):
    schema = df.schema
    # Strip and convert to lowercase all string columns
    df = df.with_columns(
        [
            pl.col(column).str.strip_chars().str.to_lowercase()
            if dtype == pl.Utf8 else pl.col(column)
            for column, dtype in schema.items()
        ]
    )
    # Identify columns where all values are None
    columns_to_drop = [col for col in df.columns if df[col].is_null().all()]
    df = df.drop(columns_to_drop)
    return df

In [36]:
class NVS:
    def __init__():
        self.modulator = self.clean_df(pl.read_excel("nvs.xlsx",sheet_name="Modulator"))
        self.acmu = self.clean_df(pl.read_excel("nvs.xlsx",sheet_name="ACMU"))
        self.nsgu = self.clean_df(pl.read_excel("nvs.xlsx",sheet_name="NSGU"))
    def clean_df(self,df):
        schema = df.schema
        # Strip and convert to lowercase all string columns
        df = df.with_columns(
            [
                pl.col(column).str.strip_chars().str.to_lowercase().str.replace("oX","")
                if dtype == pl.Utf8 else pl.col(column)
                for column, dtype in schema.items()
            ]
        )
        # Identify columns where all values are None
        columns_to_drop = [col for col in df.columns if df[col].is_null().all()]
        df = df.drop(columns_to_drop)
        return df

In [37]:
df = clean_df(pl.read_excel("nvs.xlsx",sheet_name="Modulator"))
df

shape: (168, 81)
┌──────┬─────────────┬──────┬───────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ BAND ┆ NAME        ┆ NSGU ┆ EXP_TM    ┆ … ┆ SA5_DATA61 ┆ SA5_DATA62 ┆ SA5_DATA63 ┆ SA5_DATA64 │
│ ---  ┆ ---         ┆ ---  ┆ ---       ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ str  ┆ str         ┆ str  ┆ str       ┆   ┆ str        ┆ str        ┆ str        ┆ str        │
╞══════╪═════════════╪══════╪═══════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ l5   ┆ hdcode-map1 ┆ m    ┆ l5modw1w2 ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ l5   ┆ hdcode-map2 ┆ m    ┆ l5modw1w2 ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ l5   ┆ hdcode-map3 ┆ m    ┆ l5modw1w2 ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ l5   ┆ hdcode-map4 ┆ m    ┆ l5modw1w2 ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ l5   ┆ cemic-map5  ┆ m    ┆ l5modw1w2 ┆ … ┆ 0x03       ┆ 0xe6       ┆ 0x01       ┆ 0x63       │
│ …    ┆ …           ┆ …    ┆ …         ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ s    ┆ cfg13       ┆ r    ┆ smodw1w2  ┆ … ┆ 0x03       ┆ 0x69       ┆ 0x03       ┆ 0x69       │
│ s    ┆ cfg14       ┆ r    ┆ smodw1w2  ┆ … ┆ 0x03       ┆ 0x69       ┆ 0x03       ┆ 0x69       │
│ s    ┆ cfg15       ┆ r    ┆ smodw1w2  ┆ … ┆ 0x03       ┆ 0x69       ┆ 0x03       ┆ 0x69       │
│ s    ┆ cfg16       ┆ r    ┆ smodw1w2  ┆ … ┆ 0x02       ┆ 0x00       ┆ 0x02       ┆ 0x00       │
│ s    ┆ cfg17       ┆ r    ┆ smodw1w2  ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
└──────┴─────────────┴──────┴───────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [82]:
df = df.with_columns(
    pl.concat_str([pl.col("BAND"), pl.col("NAME"),pl.col("NSGU")], separator="_").alias("TC")
)

In [19]:
x =df.filter(pl.col("TC") == "l5_hdcode-map1_m")
x

shape: (1, 82)
┌──────┬─────────────┬──────┬───────────┬───┬────────────┬────────────┬────────────┬──────────────────┐
│ BAND ┆ NAME        ┆ NSGU ┆ EXP_TM    ┆ … ┆ SA5_DATA62 ┆ SA5_DATA63 ┆ SA5_DATA64 ┆ TC               │
│ ---  ┆ ---         ┆ ---  ┆ ---       ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---              │
│ str  ┆ str         ┆ str  ┆ str       ┆   ┆ str        ┆ str        ┆ str        ┆ str              │
╞══════╪═════════════╪══════╪═══════════╪═══╪════════════╪════════════╪════════════╪══════════════════╡
│ l5   ┆ hdcode-map1 ┆ m    ┆ l5modw1w2 ┆ … ┆ null       ┆ null       ┆ null       ┆ l5_hdcode-map1_m │
└──────┴─────────────┴──────┴───────────┴───┴────────────┴────────────┴────────────┴──────────────────┘

In [44]:
 y = x.select(pl.col("^SA4.*$").drop_nulls()).row(0)
y = [ x.replace("0x","") for x in y]
y

['sendtcp', '1553trantmtcbus', '00a4', '00', '00', '00', '00']

In [40]:
y[0:3]

('sendtcp', '1553trantmtcbus', '0x00a4')

In [42]:
y[2].replace("0x","")

'00a4'

In [47]:
" ".join(y[0:3])

'sendtcp 1553trantmtcbus 00a4'

In [53]:
print("\n".join([f"Data_Byte {code};" for code in y[3:]])[:-1]+"\n")

Data_Byte 00;
Data_Byte 00;
Data_Byte 00;
Data_Byte 00

In [131]:
command_df = df.filter(pl.col("TC") == "l5_hdcode-map1_ms")
sa4_cmd = cmd_df.select(pl.col("^SA8.*$").drop_nulls()).height
#print(generate_sendtcp_command("005",sa4_cmd))
sa4_cmd

0

In [76]:
def generate_sendtcp_command(line_number,command_data):
    #Input
    #['sendtcp', '1553trantmtcbus', '00a4', '00', '00', '00', '00']
    #Output
    # 001 sendtcp 1553trantmtcbus 00a4;
    #                 Data_Byte 00;
    #                 Data_Byte 00;
    #                 Data_Byte 00;
    #                 Data_Byte 00
    procedure = ""
    command_data = [x.replace("0x","") for x in command_data]
    cmd = line_number+" "+" ".join(command_data[0:3])
    procedure += cmd+";\n"
    procedure += "\n".join([f"{' '*(len(cmd)-12)}Data_Byte {code};" for code in command_data[3:]])[:-1]+"\n"
    return procedure

In [100]:
expected_tms = cmd_df["EXP_TM"][0].split(",")
expected_values =cmd_df["EXP_TM_VAL"][0].split(",")
if len(expected_tms) != len(expected_values):
    raise Exception(f"Expected TM number of mnemonics and values mismatch in nvs.xlsx for mnemonics:{expected_tms}")

procedure =""
for i,tm in enumerate(expected_tms):
    if i==0:
        procedure += f"001 expected tm {tm}={expected_values[i]}"

In [116]:
if command_df["EXP_TM"][0] is not None and command_df["EXP_TM_VAL"][0] is not None:
    expected_tms = command_df["EXP_TM"][0].split(",")
    expected_values =[x.replace("0x","") for x in command_df["EXP_TM_VAL"][0].split(",")]
    if len(expected_tms) != len(expected_values):
        raise Exception(f"Expected TM number of mnemonics and values mismatch in nvs.xlsx for mnemonics:{expected_tms}")
    procedure =""
    for i,tm in enumerate(expected_tms):
        if i==0:
            procedure += f"001 expected tm {tm}={expected_values[i]};\n"
        else:
            procedure += f"{' '*16}{tm}={expected_values[i]};\n"
    if len(procedure) > 0:
        procedure = procedure[:-2]+"\n"
    print(procedure)

001 expected tm puncturing=enable

In [109]:
print(procedure)

001 expected tm l5modw1w2=00000002

In [107]:
[x.replace("0x","") for x in command_df["EXP_TM_VAL"][0].split(",")]

['00000002']

In [110]:
df = clean_df(pl.read_excel("nvs.xlsx",sheet_name="NSGU"))
df

shape: (19, 139)
┌────────────────┬────────────────┬────────────┬───────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ TC             ┆ EXP_TM         ┆ EXP_TM_VAL ┆ INJ_TM        ┆ … ┆ SA4_DATA61 ┆ SA4_DATA62 ┆ SA4_DATA63 ┆ SA4_DATA64 │
│ ---            ┆ ---            ┆ ---        ┆ ---           ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ str            ┆ str            ┆ str        ┆ str           ┆   ┆ str        ┆ str        ┆ str        ┆ str        │
╞════════════════╪════════════════╪════════════╪═══════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ data_on_short_ ┆ null           ┆ null       ┆ 1553_nsgu_dat ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ code           ┆                ┆            ┆ a             ┆   ┆            ┆            ┆            ┆            │
│ data_off       ┆ null           ┆ null       ┆ 1553_nsgu_dat ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│                ┆                ┆            ┆ a             ┆   ┆            ┆            ┆            ┆            │
│ puncturing_ena ┆ puncturing     ┆ enable     ┆ null          ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ ble            ┆                ┆            ┆               ┆   ┆            ┆            ┆            ┆            │
│ puncturing_dis ┆ puncturing     ┆ disable    ┆ null          ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ able           ┆                ┆            ┆               ┆   ┆            ┆            ┆            ┆            │
│ short_code     ┆ cur-rsdatastru ┆ short      ┆ 1553_nsgu     ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│                ┆ c              ┆            ┆               ┆   ┆            ┆            ┆            ┆            │
│ …              ┆ …              ┆ …          ┆ …             ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ nsgu-page1     ┆ navdatasts     ┆ tm-page1   ┆ null          ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ sps_rs_shortco ┆ null           ┆ null       ┆ null          ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ de_prn11       ┆                ┆            ┆               ┆   ┆            ┆            ┆            ┆            │
│ long_code_prn1 ┆ null           ┆ null       ┆ null          ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ 1              ┆                ┆            ┆               ┆   ┆            ┆            ┆            ┆            │
│ encryption_192 ┆ null           ┆ null       ┆ null          ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ _longrsd       ┆                ┆            ┆               ┆   ┆            ┆            ┆            ┆            │
│ encryption_256 ┆ null           ┆ null       ┆ null          ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ _longkds_longr ┆                ┆            ┆               ┆   ┆            ┆            ┆            ┆            │
│ sp…            ┆                ┆            ┆               ┆   ┆            ┆            ┆            ┆            │
└────────────────┴────────────────┴────────────┴───────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [115]:
command_df = df.filter(pl.col("TC") == "puncturing_enable")

In [118]:
class ProcedureBase:
    def __init__(self):
        self.line_number = 1
        self.r = None
        self.number_of_spaces_before_command = 20
        self.line_number_length = 3

    def get_spaces(self,ccl_command=None):
        if ccl_command:
            #print(ccl_command,(self.number_of_spaces_before_command-len(ccl_command)-self.line_number_length-1))
            return " "*(self.number_of_spaces_before_command-len(ccl_command)-self.line_number_length-1)
        else:
            return " "*self.number_of_spaces_before_command
        
    def offset_line_number(self,offset):
        self.line_number += offset

    def get_line_number(self):
        line_number = str(self.line_number).zfill(3)
        self.line_number += 1 
        return line_number



    async def inject_tm(self, tm: str,value: str):
        self.r.hset("INJECTED_TM_FOR_SIMULATOR_MAP", tm, value)
        

    async def inject_tc(self, tc: str, value: str):
        data = { "cmd":tc,"code":value,"full_code": value,"data_part": value,"status":"sucees"}
        self.r.hset("INJECTED_TC_FOR_SIMULATOR_MAP", tc, json.dumps(data))

    
    def clean_dataframe(self,df):
        schema = df.schema
        # Strip and convert to lowercase all string columns
        df = df.with_columns(
            [
                pl.col(column).str.strip_chars().str.to_lowercase().str.replace("oX","")
                if dtype == pl.Utf8 else pl.col(column)
                for column, dtype in schema.items()
            ]
        )
        # Identify columns where all values are None
        columns_to_drop = [col for col in df.columns if df[col].is_null().all()]
        df = df.drop(columns_to_drop)
        return df

In [210]:


class Nvs(ProcedureBase):
    def __init__(self):
        ProcedureBase.__init__(self)
        self.modulator = self.clean_dataframe(pl.read_excel("nvs.xlsx",sheet_name="MODULATOR"))
        self.acmu = self.clean_dataframe(pl.read_excel("nvs.xlsx",sheet_name="ACMU"))
        self.nsgu = self.clean_dataframe(pl.read_excel("nvs.xlsx",sheet_name="NSGU"))
        self.dfs = [self.modulator,self.acmu,self.nsgu]
        self.sub_address = [1,2,3,4,5]
        self.sub_system = ["MODULATOR","ACMU","NSGU"]
        
    def generate_sendtcp_command(self,command_data)->str:
        #Input
        #['sendtcp', '1553trantmtcbus', '00a4', '00', '00', '00', '00']
        #Output
        # 001 sendtcp 1553trantmtcbus 00a4;
        #                 Data_Byte 00;
        #                 Data_Byte 00;
        #                 Data_Byte 00;
        #                 Data_Byte 00
        procedure = ""
        command_data = [str(x).replace("0x","") for x in command_data]
        cmd = self.get_line_number()+" "+" ".join(command_data[0:3])
        procedure += cmd+";\n"
        procedure += "\n".join([f"{' '*(len(cmd)-12)}Data_Byte {code};" for code in command_data[3:]])[:-1]+"\n"
        return procedure
    
    def generate_expected_ccl(self, command_df: pl.DataFrame)->str:
        procedure =""
        if command_df["EXP_TM"][0] is not None and command_df["EXP_TM_VAL"][0] is not None:
            expected_tms = command_df["EXP_TM"][0].split(",")
            expected_values =[str(x).replace("0x","") for x in command_df["EXP_TM_VAL"][0].split(",")]
            if len(expected_tms) != len(expected_values):
                raise Exception(f"Expected TM number of mnemonics and values mismatch in nvs.xlsx for mnemonics:{expected_tms}")
            procedure =""
            for i,tm in enumerate(expected_tms):
                if i==0:
                    procedure += f"{self.get_line_number()} expected tm {tm}={expected_values[i]};\n"
                else:
                    procedure += f"{' '*16}{tm}={expected_values[i]};\n"
            if len(procedure) > 0:
                procedure = procedure[:-2]+"\n"
        return procedure

    def get_remark(self,system,cmd,is_start=True):
        overall_length = 80
        if is_start:
            header = f"{system} 1553 CMD for:{cmd}"
            no_of_stars =int( (overall_length-len(header))/2)
            return f"!{'*'*no_of_stars}{header}{'*'*no_of_stars}\n\n"
        else:
            header = f"END of 1553 CMD"
            no_of_stars = int((overall_length-len(header))/2)
            return f"\n!{'*'*no_of_stars}{header}{'*'*no_of_stars}\n"
        
    
    def get_procedure(self, command) -> str:
        procedure = ""
        system =""
        command_df = None
        c=-1
        for df in self.dfs:
            command_df = df.filter(pl.col("TC") == command.lower())
            c += 1
            if command_df.height > 0:
                break
        system = self.sub_system[c]
        if command_df is None:
            raise Exception(f"Command:{command} Not Found in nvs.xlsx")
    
        procedure += self.generate_expected_ccl(command_df)
        if len(procedure):
            procedure += "\n"
        for i in self.sub_address:
            search_exp = f"^SA{i}.*$"
            sa_cmd = command_df.select(pl.col(search_exp).drop_nulls())
            if sa_cmd.height > 0:
                procedure += self.generate_sendtcp_command(sa_cmd.row(0))+"\n"
        if len(procedure) > 0:
            procedure = self.get_remark(system,command)+procedure+self.get_remark(system,command,False)
        
        return procedure

In [211]:
obj = Nvs()

In [214]:
print(obj.get_procedure("Long_Code"))

!**************************NSGU 1553 CMD for:Long_Code**************************

007 expected tm cur-rsdatastruc=long

008 sendtcp 1553trantmtcbus 0083;
                    Data_Byte 00;
                    Data_Byte 07;
                    Data_Byte 00;
                    Data_Byte 93;
                    Data_Byte 00;
                    Data_Byte 01;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00

009 sendtcp 1553trantmtcbus 0083;
                    Data_Byte 00;
                    Data_Byte 07;
                    Data_Byte 00;
                    Data_Byte 26;
                    Data_Byte 00;
                    Data_Byte 01;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte a0;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 00;
                    Data_Byte 55


!********************************END of 1553 CMD********************************

In [161]:
obj.acmu

shape: (1, 20)
┌────────────────┬───────────────┬───────────────┬───────────┬───┬───────────────┬─────────────┬───────────┬───────────┐
│ TC             ┆ EXP_TM        ┆ EXP_TM_VAL    ┆ INJ_TM    ┆ … ┆ SA3_CMD_TYPE  ┆ SA3_ADDRESS ┆ SA3_DATA1 ┆ SA3_DATA2 │
│ ---            ┆ ---           ┆ ---           ┆ ---       ┆   ┆ ---           ┆ ---         ┆ ---       ┆ ---       │
│ str            ┆ str           ┆ str           ┆ str       ┆   ┆ str           ┆ str         ┆ str       ┆ str       │
╞════════════════╪═══════════════╪═══════════════╪═══════════╪═══╪═══════════════╪═════════════╪═══════════╪═══════════╡
│ synt_inp_rafs2 ┆ synth-i/p-sel ┆ irafs1,rrafs2 ┆ 1553_acmu ┆ … ┆ 1553trantmtcb ┆ 0x0023      ┆ 0x00      ┆ 0x14      │
│                ┆ ,phase-mtri/p ┆ ,2,present,lo ┆           ┆   ┆ us            ┆             ┆           ┆           │
│                ┆ sel,…         ┆ ck,l…         ┆           ┆   ┆               ┆             ┆           ┆           │
└────────────────┴───────────────┴───────────────┴───────────┴───┴───────────────┴─────────────┴───────────┴───────────┘

In [189]:
'*'*2

'**'

In [220]:
len(set(["a","b"]) & set(["a","b"]))

2

In [230]:
import requests

In [255]:
data = {"topic":"com.tc_file.status","msg":{ "summary":"summary","status":"status10","progress": "10" }}
requests.post(url = "http://127.0.0.1/publish_to_wamp",json= data)

NameError: name 'cnxn' is not defined